### ISSUE TITLE
Jinja2 exception on adding new fields to register

### ISSUE THREAD

**Issue by veeshi** [jwag956/flask-security#122]
Thanks for taking over the maintenance of Flask-Security!

I tried extending the registration form but I am getting the following error:
```Traceback (most recent call last):
  File "/home/user/virtualenv/dev/3.5/lib/python3.5/site-packages/flask/app.py", line 2328, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/user/virtualenv/dev/3.5/lib/python3.5/site-packages/flask/app.py", line 2314, in wsgi_app
    response = self.handle_exception(e)
  File "/home/user/virtualenv/dev/3.5/lib/python3.5/site-packages/flask/app.py", line 1760, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/virtualenv/dev/3.5/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/user/virtualenv/dev/3.5/lib/python3.5/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/virtualenv/dev/3.5/lib/python3.5/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/virtualenv/dev/3.5/lib/python3.5/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/virtualenv/dev/3.5/lib/python3.5/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/home/user/virtualenv/dev/3.5/lib/python3.5/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/virtualenv/dev/3.5/lib/python3.5/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/virtualenv/dev/3.5/lib/python3.5/site-packages/flask_security/decorators.py", line 254, in wrapper
    return f(*args, **kwargs)
  File "/home/user/virtualenv/dev/3.5/lib/python3.5/site-packages/flask_security/views.py", line 185, in register
    **_ctx("register")
  File "/home/user/virtualenv/dev/3.5/lib/python3.5/site-packages/flask_security/core.py", line 728, in render_template
    return render_template(*args, **kwargs)
  File "/home/user/virtualenv/dev/3.5/lib/python3.5/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/user/virtualenv/dev/3.5/lib/python3.5/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/user/virtualenv/dev/3.5/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/user/virtualenv/dev/3.5/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/virtualenv/dev/3.5/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/user/dev/templates/security/register_user.html", line 1, in top-level template code
    {% extends "white-base.html" %}
  File "/home/user/dev/templates/white-base.html", line 78, in top-level template code
    {% block content %}
  File "/home/user/dev/templates/security/register_user.html", line 82, in block "content"
    {{ render_field_with_errors(register_user_form.first_name,placeholder="First Name",class="input-form-field form-control",spellcheck="false") }}
  File "/home/user/virtualenv/dev/3.5/lib/python3.5/site-packages/jinja2/runtime.py", line 579, in _invoke
    rv = self._func(*arguments)
  File "/home/user/dev/templates/security/_macros.html", line 2, in template
    {% if field.errors %}
  File "/home/user/virtualenv/dev/3.5/lib/python3.5/site-packages/jinja2/environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'flask_security.forms.ConfirmRegisterForm object' has no attribute 'first_name'
```

I'm not sure what the issue is as I've made an extended registration form and called it too.
`security = Security(app, user_datastore, register_form=ExtendedRegisterForm)`

I've seen [this]( https://github.com/mattupstate/flask-security/issues/54) issue in the original repo however I'm not sure if it is related or what the fix is.

Any help would be appreciated.

**Comment by jwag956** [comment]
It likely is the same issue - however hard to say since you haven't provided any code or configuration variables. But one question - since it appears you have SECURITY_CONFIRMABLE set - you should try overriding the confirm_register_form rather than the register_form.

**Comment by rhaamo** [comment]
I also have overriden form and it works.

The `'flask_security.forms.ConfirmRegisterForm object' has no attribute 'first_name'` let me think it's using `ConfirmRegisterForm` instead of `RegisterForm`, I do think the Confirm one is only for the confirmation part, not registration itself.

I am using this for the registration but not sure I tried it explicitly with the **confirmation** flow:

```python
from forms import ExtendedRegisterForm
    security = Security(  # noqa: F841
        app, user_datastore, register_form=ExtendedRegisterForm, confirm_register_form=ExtendedRegisterForm
    )
```

```python
from flask_security import RegisterForm
class ExtendedRegisterForm(RegisterForm):
    name = StringField(lazy_gettext("Username"), [DataRequired(), Regexp(regex=r"^\w+$"), Length(max=150)])
    def validate_name ...
```

```jinja2
            {{ bf4.render_form(register_user_form, action=url_for_security('register'), horizontal_columns=('lg', 3, 5), form_type='horizontal', button_map={'submit': 'success'}) }}
```

**Comment by jwag956** [comment]
Thanks - you overrode both forms - which is probably why it works.
The 'ConfirmRegisterForm' is confusing - since if you look at it - it DOESN'T force retyping/confirming password. In this case 'Confirm' means you have the SECURITY_CONFIRMABLE flag set - at which point it ALWAYS uses the ConfirmRegisterForm and not the RegisterForm.
As Matt stated in the original issue - he felt that forcing additional input of password, if you are asking for email confirmation was burdensome. In modern UIs I have seen, UX folks have moved away from forcing retyping passwords and opting instead for making it easy to reset your password if you forget it. I like that model and use it in my app..

**Comment by veeshi** [comment]
I have only overrode one form.

**Comment by jwag956** [comment]
Right - since I believe you have SECURITY_CONFIRMABLE set - please override confirm_register_form=ExtendedRegisterationForm...

**Comment by veeshi** [comment]
Yes apologies in my config I do have SECURITY_CONFIRMABLE  set :). Can this be added to the documentation?

**Comment by najibfahs** [comment]
I have the same problem and it got fixed by overriding the default confirmRegister with the extended RegisterForm:
_security = Security(app, user_datastore, register_form=ExtendedRegisterForm, confirm_register_form=ExtendedRegisterForm)_

is this a clean fix to a bug in the code?
